services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.99.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ~/.config/gcloud/application_default_credentials.json:/etc/otel/key.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/otel/key.json
    ports:
      # - "1888:1888"   # pprof extension
      # - "8888:8888"   # Prometheus metrics exposed by the collector
      # - "8889:8889"   # Prometheus exporter metrics
      # - "13133:13133" # health_check extension
      # - "127.0.0.1:4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      # - "55679:55679" # zpages extension
  jaeger:
    container_name: jaegertracing
    image: jaegertracing/all-in-one:latest
    ports:
      # https://www.jaegertracing.io/docs/latest/getting-started/
      - 16686:16686 # frontend
      - 14250:14250 # accept model.proto
