receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/googlecloudexporter

  # For local debug
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/jaegerexporter
  jaeger:
    endpoint: jaegertracing:14250
    tls:
      insecure: true
  # googlecloud:
  #   project: YOUR_PROJECT_ID
  #   retry_on_failure:
  #     enabled: false
  #   trace:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger]
      # exporters: [logging, googlecloud]
