name: CI

on:
  pull_request:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - name: Build the Docker image
      run: docker buildx bake -f compose-all-in-one.yml --progress=plain
      
  build-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: 'npm'
      - run: npm ci
      - run: npm run build

  test-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: 'npm'
      - run: npm ci

      - name: Show docker and compose version
        run: |
          docker version
          docker compose version

      - name: Unit test
        run: npm run test
      - name: Integrate test
        run: npm run test:integrate
